### ISSUE TITLE
空行やインデントはスタイルガイドに準拠しよう

### ISSUE THREAD

**Issue by norotime** [uniqorn-ewi/favtune#13]
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/views/layouts/application.html.erb#L11

https://google.github.io/styleguide/htmlcssguide.html#HTML_Style_Rules

**Comment by norotime** [comment]
@uniqorn-ewi ERBの記述のインデント崩れが散見され、非常に気になりました。チェックをお願いしますねーー。
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/views/sessions/_form_new.html.erb#L8

**Comment by uniqorn-ewi** [comment]
イシューをコミットメッセージでクローズ出来なかったので
サイト側でクローズ。
