### ISSUE TITLE
同一環境のグルーピングにまとめて記述しよう

### ISSUE THREAD

**Issue by norotime** [uniqorn-ewi/favtune#2]
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/Gemfile#L39

同じ環境グループを複数記述するのはDRYの観点から推奨されません。

**Comment by norotime** [comment]
この辺もですね。
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/Gemfile#L66

**Comment by uniqorn-ewi** [comment]
イシューをコミットメッセージでクローズ出来なかったので
サイト側でクローズ。
