### ISSUE TITLE
不要なコードは削除しておこう

### ISSUE THREAD

**Issue by norotime** [uniqorn-ewi/favtune#7]
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/controllers/favorites_controller.rb#L2

@uniqorn-ewi 再利用する予定があるのであれば、別です。

**Comment by norotime** [comment]
この辺もですね。
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/controllers/favorites_controller.rb#L18

**Comment by norotime** [comment]
@uniqorn-ewi コメントアウトが非常に多いと感じます。現場では、やめましょう。
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/controllers/users_controller.rb#L58

**Comment by norotime** [comment]
他にもありますので、チェックをお願いします。

**Comment by uniqorn-ewi** [comment]
コメントアウトにしているソースファイルの修正完了。
