### ISSUE TITLE
アソシエーションメソッドを使い一行で記述しよう

### ISSUE THREAD

**Issue by norotime** [uniqorn-ewi/favtune#8]
https://github.com/uniqorn-ewi/favtune/blob/b70eb4b50c3e720036426ede0717061670e2fb87/app/controllers/radio_stations_controller.rb#L18

https://railsguides.jp/association_basics.html#has-many%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89-collection-build-attributes

**Comment by uniqorn-ewi** [comment]
コミットメッセージの入力ミスのため、サイトにサインインしてクローズ。
